Fix setup.py’s CommandMixin.copy_file using ancient method signature
The CommandMixin.copy_file in the setup.py file used an ancient
signature from the times of Python 2.x I believe.  This resulted in

    TypeError: copy_file() got an unexpected keyword argument 'verbose'
    TypeError: copy_file() got an unexpected keyword argument 'dry_run'

exceptiens when trying to build a new release.  Use new signature
which no longer has `verbose` and `dry_run` arguments.